version: '3.9.6'
services:
  app:
    build: 
      context: ./docker
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/django-tech-test
    ports:
      - 8000:8000
